apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - msa-app-deployment.yaml
  - msa-app-service.yaml
  - msa-configmap.yaml
  - msa-secret.yaml

images:
  - name: msa
    newName: msa
    newTag: 1.0.0
